### ISSUE TITLE
not compatible with VS Code '1.50.1'.

### ISSUE THREAD

**Issue by bobpaul** [rolandostar/tabletopsimulator-lua-vscode#13]
Tried to install from VSIX and received this error:

Unable to install extension 'rolandostar.tabletopsimulator-lua' as it is not compatible with VS Code '1.50.1'.

![image](https://user-images.githubusercontent.com/90864/98564736-5570bd00-2272-11eb-8051-ede99edf078a.png)

**Comment by rolandostar** [comment]
Hello!
I'll be pushing an update this week that addresses this issue.

Thanks for the report!
