### ISSUE TITLE
Install Console++ deleted my workspace

### ISSUE THREAD

**Issue by nikklassen** [rolandostar/tabletopsimulator-lua-vscode#14]
I'm not sure what happened, I'm using windows (latest version of VS Code) and the Install Console++ command just called `rmdir` on my workspace, deleting everything other than the folder itself.

**Comment by rolandostar** [comment]
Did this happen to the "Tabletop Simulator Scripts" folder?
The contents of this folder are temporary since they are retrieved from the game, any files not present in the current save file would be deleted.
If this happened to any other folder let me know since that would be a bug.

**Comment by nikklassen** [comment]
Yes, it all the files under `C:\Users\Nik\Documents\Tabletop Simulator\`

**Comment by rolandostar** [comment]
I'll check it out, thanks

**Comment by nikklassen** [comment]
Thanks for getting a fix in so quickly!

**Comment by rolandostar** [comment]
No problem, unwanted deletes are high priority. Thank you for reporting it.
