### ISSUE TITLE
XML <Include> replacement occurs even when the <Include> is commented out.

### ISSUE THREAD

**Issue by cariehl** [rolandostar/tabletopsimulator-lua-vscode#18]
In the following example, after performing a Save and Play operation, I get a VS Code error: "Cyclical include detected. b.xml was previously included". I also get a TTS error: "Error Building XML UI on Global: An XML comment cannot contain '--', and '-' cannot be the last character. Line 2, position 8."

a.xml:
```
<!-- <Include src="b.xml" /> -->

<Panel />
```

b.xml:
```
<Panel />
```

Global.xml:
```
<Include src="a.xml" />
<Include src="b.xml" />
```

Global.xml (within TTS, after performing Save and Play):
```
<!-- include a.xml -->
<!-- <!-- include b.xml -->
<Panel />
<!-- include b.xml --> -->

<Panel />
<!-- include a.xml -->
```

(Note that b.xml must not be empty in order to reproduce this issue, since the extension apparently does not perform `<Include>` replacement if the target file is empty).

This appears to be because the extension is performing `<Include>` text replacement when parsing "a.xml", even though the `<Include>` tag is commented out. I glanced at the code, and it looks like the culprit is the regex found in [this function](https://github.com/rolandostar/tabletopsimulator-lua-vscode/blob/6422e8afed584727d75dde50a9b763994df22ed1/src/TTSAdapter.ts#L548).

I would imagine that we only want to perform `<Include>` replacement if the tag is not inside a comment? The current implementation makes it slightly annoying to comment out `<Include>` tags for debugging purposes.

**Comment by rolandostar** [comment]
I can confirm this is an issue, I'll be working on it this weekend. Thank you for reporting it.
