### ISSUE TITLE
Save and Play doesn't work when "Clear on Reload" is active

### ISSUE THREAD

**Issue by Sebaestschjin** [rolandostar/tabletopsimulator-lua-vscode#26]
When the setting "Clear on Reload" is enabled, Save and Play doesn't work anymore. There's no error message.

The reason for this behavior, is the following wrong `else` case:
https://github.com/rolandostar/tabletopsimulator-lua-vscode/blob/master/src/TTSAdapter.ts#L238-L239

**Comment by rolandostar** [comment]
Fixed in 2.0.0, release pending
