### ISSUE TITLE
Style the search button in docs

### ISSUE THREAD

**Issue by AucaCoyan** [rolandostar/tabletopsimulator-lua-vscode#32]
I really like the styles search buttons, like this one:

![image](https://user-images.githubusercontent.com/30557287/195635984-73fbefd2-080a-44b7-b9b8-207f0f773f4b.png)

I was looking how to do it, when I stumble upon the [Docusaurus official support of Algolia](https://docusaurus.io/docs/search).

Are there plans to apply to this search? only the owner @rolandostar is able to do it.

If it's not the case, we should [implement our own DocSearch crawler](https://docsearch.algolia.com/docs/legacy/run-your-own/). It's not impossible, but I think is an overkill for this size of open-source project.

**Comment by AucaCoyan** [comment]
It is showing as you captured, but I meant the style of the button. The top-right shows sort of "cropped out". I will investigate further

**Comment by rolandostar** [comment]
Right, there is the `custom.css` file where I can write the fix with a selector targeting that search bar. I'll try to address it this weekend. :)

**Comment by AucaCoyan** [comment]
don't worry @rolandostar ! Let me do the job. You are fighting with other stuff at this repos right now 😂 .
