### ISSUE TITLE
Incorporate `prettier` formatting for `.md` files in the docs publish pipeline

### ISSUE THREAD

**Issue by AucaCoyan** [rolandostar/tabletopsimulator-lua-vscode#34]
From another issue, I'd be cool if we can incorporate `prettier` formatting for `.md` files in the docs publish pipeline

_Originally posted by @rolandostar in https://github.com/rolandostar/tabletopsimulator-lua-vscode/issues/31#issuecomment-1278346081_

**Comment by AucaCoyan** [comment]
First issue #35 should be addressed before working on this

**Comment by rolandostar** [comment]
Linting docs is now part of the pipeline 👍
