### ISSUE TITLE
`#include` doesn't completely work

### ISSUE THREAD

**Issue by greeze** [rolandostar/tabletopsimulator-lua-vscode#4]
Currently, only a single `#include` statement as the first line of the file appears to work. Multiple includes don't work, nor does placing an `#include` statement at the end of a file. Nested includes are also not working.

**Comment by HowdyMcGee** [comment]
I too have this issue. The first file will get included but the 2nd throws the error: `unexpected symbol near '#'`

**Comment by jonahwh** [comment]
I opened #8 to fix this. As a temporary workaround, use `%include` instead of `#include` in your script.
