### ISSUE TITLE
require() support

### ISSUE THREAD

**Issue by Benjamin-Dobell** [rolandostar/tabletopsimulator-lua-vscode#5]
The latest Atom plugin has support for Lua bundling using `require("module")`. `#include` still works but will likely be deprecated at some point in the future. Rather than worry about https://github.com/rolandostar/tabletopsimulator-lua-vscode/issues/4 it may be pertinent to just go straight to `require()` and skip `#include` support.

I wrote [luabundle](https://github.com/Benjamin-Dobell/luabundle) specifically with the intention that VSCode plugins would be able to consume this just the [same as the official Atom TTS plugin](https://github.com/Berserk-Games/atom-tabletopsimulator-lua/blob/master/lib/tabletopsimulator-lua.coffee#L317-L388).

luabundle will do all the heavy lifting, is [thoroughly documented](https://github.com/Benjamin-Dobell/luabundle/blob/master/README.md) and has TypeScript type definitions. So _hopefully_ it should be pretty straight-forward to implement.

If you want to have chat about the above you can typically find me in the #scripting channel of the official TTS Discord.

**Comment by rolandostar** [comment]
Thanks for the heads-up. I'll definitely check it out.
